# Generated by Django 3.0.4 on 2020-03-26 00:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='DUN')),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='address1',
            field=models.CharField(max_length=200, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='address2',
            field=models.CharField(max_length=200, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Complicated', 'Complicated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='nric',
            field=models.CharField(max_length=12, null=True, verbose_name='NRIC No.'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='postal_code',
            field=models.CharField(max_length=5, null=True, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='salutation',
            field=models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms')], max_length=10, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.CharField(choices=[('JOHOR', 'Johor'), ('KEDAH', 'Kedah'), ('KELANTAN', 'Kelantan'), ('MELAKA', 'Melaka'), ('NEGERI SEMBILAN', 'Negeri Sembilan'), ('PAHANG', 'Pahang'), ('PULAU PINANG', 'Pulau Pinang'), ('PERAK', 'Perak'), ('PERLIS', 'Perlis'), ('SABAH', 'Sabah'), ('SARAWAK', 'Sarawak'), ('SELANGOR', 'Selangor'), ('TERENGGANU', 'Terengganu'), ('W.P. KUALA LUMPUR', 'Kuala Lumpur'), ('W.P. LABUAN', 'Labuan'), ('W.P. PUTRAJAYA', 'Putrajaya')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Applicant')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Product')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='dun',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Dun'),
        ),
    ]
