# Generated by Django 3.0.4 on 2020-03-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_dun_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='dun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Dun'),
        ),
    ]
